name: quickexpression
description: an expression evalutator for dart
version: 1.0.0
homepage: https://github.com/liuzg50505/quickexpression
author: liuzg <liuzg50505@qq.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
